//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEResourceConfigurationWidget.cpp
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

#include "ZEResourceConfigurationWidget.h"
#include "ui_ZEResourceConfigurationWidget.h"
#include "ZEResourceOptionTreeItem.h"
#include "QtGui/QTreeWidgetItem"
#include "ZEML/ZEMLNode.h"
#include "ZEFile/ZEFile.h"
#include "ZEFile/ZEFileCommon.h"
#include "ZEML/ZEMLProperty.h"
#include "ZEResourceConfigurationWidgetQt.h"

#include <time.h>
#include "ZEResourceConfigurator/ZEResourceConfigurator.h"

inline static time_t GetTime(ZEFileTime* Date)
{
	struct tm CDate;
	memset(&CDate, 0, sizeof(struct tm));

	CDate.tm_year = Date->Year - 1900;
	CDate.tm_mon = Date->Month;
	CDate.tm_mday = Date->Day;
	CDate.tm_hour = Date->Hour;
	CDate.tm_min = Date->Minute;
	CDate.tm_sec = Date->Second;

	return mktime(&CDate);
}

ZEResourceConfigurationWidget::ZEResourceConfigurationWidget(QWidget* Parent)
{
	QtComponents = new ZEResourceConfigurationWidgetQt(this, Parent);
}

ZEResourceConfigurationWidget::~ZEResourceConfigurationWidget()
{
	//delete QtComponents; Possibly causing crash.
}

void ZEResourceConfigurationWidget::AddResource(const ZEString& Identifier, const ZEString& Type, const ZEString& PhysicalPath, const ZEString& ExportPath, ZEResourceOptionAvailableAction Action, bool IsAutoGenerated)
{
	if(PhysicalPath == "C:\\Users\\Can\\Desktop\\CustHFiles\\Base\\DamagedCity\\ShopG.jpg")
		PhysicalPath.GetLength();

	if(Identifier.GetLength() == 0)
	{
		zeLog("Resource identifier can not be NULL.");
		return;
	}

	zeLog(Identifier.ToCString());
	zeLog(Type.ToCString());

	if(PhysicalPath.GetLength() != 0)
		zeLog(PhysicalPath.ToCString());

	if(!IsAutoGenerated && PhysicalPath.GetLength() == 0)
		zeLog("Non auto generated resource physical path can not be empty.");

	ZEResourceOption* TempOption = NULL;
	
	if(Configurator.GetOption(Identifier, TempOption))
	{
		bool IsFound = false;

		for (ZESize I = 0; I < QtComponents->Form->ResourcesTreeWidget->topLevelItemCount(); I++)
		{
			ZEResourceOption* CurrentResourceOption = ((ZEResourceOptionTreeItem*)(QtComponents->Form->ResourcesTreeWidget->topLevelItem(I)))->GetResourceOption();

			if(CurrentResourceOption->Identifier == Identifier)
				IsFound = true;
		}

		if(!IsFound)
		{
			ZEResourceOptionTreeItem* NewItem = new ZEResourceOptionTreeItem();
			NewItem->SetResourceOption(TempOption);
			QtComponents->Form->ResourcesTreeWidget->addTopLevelItem(NewItem);
			NewItem->Update();
		}
		else
			return;
	}
	else
	{
		ZEResourceOptionTreeItem* NewItem = new ZEResourceOptionTreeItem();

		if(ExportPath.GetLength() != 0)
			Configurator.AddResource(Identifier, Type, ExportPath, PhysicalPath, Action, IsAutoGenerated);
		else
			Configurator.AddResource(Identifier, Type, DefaultExportPath, PhysicalPath, Action, IsAutoGenerated);

		Configurator.GetOption(Identifier, TempOption);
		NewItem->SetResourceOption(TempOption);
		QtComponents->Form->ResourcesTreeWidget->addTopLevelItem(NewItem);
		NewItem->Update();
	}
}

void ZEResourceConfigurationWidget::AddResource(const ZEString& Identifier, const ZEString& Type, const ZEString& ExportPath, ZEResourceOptionAvailableAction Action, bool IsAutoGenerated)
{
	AddResource(Identifier , Type, ZEString(), ExportPath, Action, IsAutoGenerated);
}

bool ZEResourceConfigurationWidget::Show()
{
	if(QtComponents->Dialog->exec() == QDialog::Accepted)
		return true;
	else
		return false;
}

void ZEResourceConfigurationWidget::Hide()
{
	QtComponents->Dialog->close();
}

const ZEArray<ZEResourceOption*>& ZEResourceConfigurationWidget::GetOptions()
{
	return Configurator.GetOptions();
}

void ZEResourceConfigurationWidget::LoadPreset(const ZEString& Path)
{
	ZEFile File;
	
	if(!File.Open(Path, ZE_FOM_READ, ZE_FCM_NONE))
		zeWarning("Preset file not found.");
	else
	{
		Configurator.LoadPresetFromFile(&File);
		File.Close();
	}
}

void ZEResourceConfigurationWidget::SavePreset(const ZEString& Path)
{
	ZEFile File;
	if(!File.Open(Path, ZE_FOM_READ_WRITE, ZE_FCM_OVERWRITE))
	{
		zeError("Can not open given file to write. File path : %s", Path.ToCString());
		return;
	}

	Configurator.SavePresetToFile(&File);
	
	if(File.IsOpen())
		File.Close();
}

bool ZEResourceConfigurationWidget::GetOption(const ZEString& Identifier, ZEResourceOption& Option)
{
	ZEResourceOption* TempOption;
	bool Result = Configurator.GetOption(Identifier, TempOption);
	
	if(Result)
	{
		Option = *TempOption;
		return true;
	}
	else
		return false;	 
}

void ZEResourceConfigurationWidget::SetZEWorkingDir(const ZEString& Path)
{
	ZinekDirectory = Path;
}

bool ZEResourceConfigurationWidget::GetCopyState(const ZEString& Identifier)
{
	return Configurator.GetResourceCopyState(Identifier);
}

ZEString ZEResourceConfigurationWidget::GetResourceRelativePath(ZEString& RelativeTo, const ZEString& Identifier)
{
	return Configurator.GetResourceRelativePath(RelativeTo, Identifier);
}

void ZEResourceConfigurationWidget::SetDefaultExportPath(ZEString Path)
{
	DefaultExportPath = Path;
}
