//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEMTTypeTestTable.h
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

ZEMT_TYPE_TEST(ZEInt8,											0xCE,										ZEMTType(ZEMT_BT_INTEGER_8, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt8,									0xCE,										ZEMTType(ZEMT_BT_INTEGER_8, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt8&,											ZEInt8(0xCE),								ZEMTType(ZEMT_BT_INTEGER_8, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt8&,									ZEInt8(0xCE),								ZEMTType(ZEMT_BT_INTEGER_8, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt16,											0xCECE,										ZEMTType(ZEMT_BT_INTEGER_16, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt16,									0xCECE,										ZEMTType(ZEMT_BT_INTEGER_16, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt16&,										ZEInt16(0xCECE),							ZEMTType(ZEMT_BT_INTEGER_16, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt16&,									ZEInt16(0xCECE),							ZEMTType(ZEMT_BT_INTEGER_16, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt32,											0xCECECECE,									ZEMTType(ZEMT_BT_INTEGER_32, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt32,									0xCECECECE,									ZEMTType(ZEMT_BT_INTEGER_32, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt32&,										ZEInt32(0xCECECECE),						ZEMTType(ZEMT_BT_INTEGER_32, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt32&,									ZEInt32(0xCECECECE),						ZEMTType(ZEMT_BT_INTEGER_32, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt64,											0xCECECECEADADADAD,							ZEMTType(ZEMT_BT_INTEGER_64, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt64,									0xCECECECEADADADAD,							ZEMTType(ZEMT_BT_INTEGER_64, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEInt64&,										ZEInt64(0xCECECECEADADADAD),				ZEMTType(ZEMT_BT_INTEGER_64, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEInt64&,									ZEInt64(0xCECECECEADADADAD),				ZEMTType(ZEMT_BT_INTEGER_64, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt8,											0xCE,										ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_8, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt8,									xCE,										ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_8, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt8&,										ZEUInt8(0xCE),								ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_8, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt8&,									ZEUInt8(0xCE),								ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_8, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt16,										0xCECE,										ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_16, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt16,									0xCECE,										ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_16, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt16&,										ZEUInt16(0xCECE),							ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_16, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt16&,									ZEUInt16(0xCECE),							ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_16, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt32,										0xCECECECE,									ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_32, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt32,									0xCECECECE,									ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_32, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt32&,										ZEUInt32(0xCECECECE),						ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_32, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt32&,									ZEUInt32(0xCECECECE),						ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_32, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt64,										0xCECECECEADADADAD,							ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_64, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt64,									0xCECECECEADADADAD,							ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_64, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEUInt64&,										ZEUInt64(0xCECECECEADADADAD),				ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_64, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEUInt64&,									ZEUInt64(0xCECECECEADADADAD),				ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_64, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(float,											0.5f,										ZEMTType(ZEMT_BT_FLOAT, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const float,										0.5f,										ZEMTType(ZEMT_BT_FLOAT, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(float&,											float(0.5f),								ZEMTType(ZEMT_BT_FLOAT, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const float&,									float(0.5f),								ZEMTType(ZEMT_BT_FLOAT, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(double,											0.5f,										ZEMTType(ZEMT_BT_DOUBLE, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const double,									0.5f,										ZEMTType(ZEMT_BT_DOUBLE, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(double&,											double(0.5f),								ZEMTType(ZEMT_BT_DOUBLE, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const double&,									double(0.5f),								ZEMTType(ZEMT_BT_DOUBLE, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(bool,											true,										ZEMTType(ZEMT_BT_BOOLEAN, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const bool,										true,										ZEMTType(ZEMT_BT_BOOLEAN, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(bool&,											bool(true),									ZEMTType(ZEMT_BT_BOOLEAN, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const bool&,										bool(true),									ZEMTType(ZEMT_BT_BOOLEAN, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEString,										"",											ZEMTType(ZEMT_BT_STRING, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEString,									"",											ZEMTType(ZEMT_BT_STRING, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEString&,										ZEString::Empty,							ZEMTType(ZEMT_BT_STRING, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEString&,									ZEString::Empty,							ZEMTType(ZEMT_BT_STRING, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector2,										ZEVector2::One,								ZEMTType(ZEMT_BT_VECTOR2, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector2,									ZEVector2::One,								ZEMTType(ZEMT_BT_VECTOR2, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector2&,										ZEVector2::One,								ZEMTType(ZEMT_BT_VECTOR2, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector2&,								ZEVector2::One,								ZEMTType(ZEMT_BT_VECTOR2, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector2d,										ZEVector2d::One,							ZEMTType(ZEMT_BT_VECTOR2D, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector2d,								ZEVector2d::One,							ZEMTType(ZEMT_BT_VECTOR2D, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector2d&,										ZEVector2d::One,							ZEMTType(ZEMT_BT_VECTOR2D, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector2d&,								ZEVector2d::One,							ZEMTType(ZEMT_BT_VECTOR2D, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector3,										ZEVector3::One,								ZEMTType(ZEMT_BT_VECTOR3, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector3,									ZEVector3::One,								ZEMTType(ZEMT_BT_VECTOR3, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector3&,										ZEVector3::One,								ZEMTType(ZEMT_BT_VECTOR3, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector3&,								ZEVector3::One,								ZEMTType(ZEMT_BT_VECTOR3, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector3d,										ZEVector3d::One,							ZEMTType(ZEMT_BT_VECTOR3D, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector3d,								ZEVector3d::One,							ZEMTType(ZEMT_BT_VECTOR3D, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector3d&,										ZEVector3d::One,							ZEMTType(ZEMT_BT_VECTOR3D, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector3d&,								ZEVector3d::One,							ZEMTType(ZEMT_BT_VECTOR3D, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector4,										ZEVector4::One,								ZEMTType(ZEMT_BT_VECTOR4, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector4,									ZEVector4::One,								ZEMTType(ZEMT_BT_VECTOR4, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector4&,										ZEVector4::One,								ZEMTType(ZEMT_BT_VECTOR4, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector4&,								ZEVector4::One,								ZEMTType(ZEMT_BT_VECTOR4, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector4d,										ZEVector4d::One,							ZEMTType(ZEMT_BT_VECTOR4D, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector4d,								ZEVector4d::One,							ZEMTType(ZEMT_BT_VECTOR4D, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEVector4d&,										ZEVector4d::One,							ZEMTType(ZEMT_BT_VECTOR4D, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEVector4d&,								ZEVector4d::One,							ZEMTType(ZEMT_BT_VECTOR4D, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEQuaternion,									ZEQuaternion::Identity,						ZEMTType(ZEMT_BT_QUATERNION, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEQuaternion,								ZEQuaternion::Identity,						ZEMTType(ZEMT_BT_QUATERNION, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEQuaternion&,									ZEQuaternion::Identity,						ZEMTType(ZEMT_BT_QUATERNION, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEQuaternion&,								ZEQuaternion::Identity,						ZEMTType(ZEMT_BT_QUATERNION, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix3x3,										ZEMatrix3x3::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix3x3,								ZEMatrix3x3::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix3x3&,									ZEMatrix3x3::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix3x3&,								ZEMatrix3x3::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix3x3d,									ZEMatrix3x3d::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3D, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix3x3d,								ZEMatrix3x3d::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3D, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix3x3d&,									ZEMatrix3x3d::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3D, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix3x3d&,								ZEMatrix3x3d::Identity,						ZEMTType(ZEMT_BT_MATRIX3X3D, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix4x4,										ZEMatrix4x4::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix4x4,								ZEMatrix4x4::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix4x4&,									ZEMatrix4x4::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix4x4&,								ZEMatrix4x4::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix4x4d,									ZEMatrix4x4d::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4D, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix4x4d,								ZEMatrix4x4d::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4D, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEMatrix4x4d&,									ZEMatrix4x4d::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4D, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEMatrix4x4d&,								ZEMatrix4x4d::Identity,						ZEMTType(ZEMT_BT_MATRIX4X4D, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZETestObject,									ZETestObject::Instance,						ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZETestObject,								ZETestObject::Instance,						ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZETestObject&,									ZETestObject::Instance,						ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZETestObject&,								ZETestObject::Instance,						ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZETestObject*,									&ZETestObject::Instance,					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZETestObject*,								&ZETestObject::Instance,					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZETestObject*&,									ZETestObject::InstancePtr,					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZETestObject*&,							ZETestObject::InstancePtr,					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEHolder<ZETestObject>,							&ZETestObject::Instance,					ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEHolder<const ZETestObject>,					&ZETestObject::Instance,					ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_CONST_VALUE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEHolder<ZETestObject>&,							&ZETestObject::Instance,					ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEHolder<const ZETestObject>&,					&ZETestObject::Instance,					ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_CONST_REFERENCE, ZEMT_CT_NONE, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZEInt8>,									ZEArray<ZEInt8>(),							ZEMTType(ZEMT_BT_INTEGER_8, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEInt16>,								ZEArray<ZEInt16>(),							ZEMTType(ZEMT_BT_INTEGER_16, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEInt32>,								ZEArray<ZEInt32>(),							ZEMTType(ZEMT_BT_INTEGER_32, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEInt64>,								ZEArray<ZEInt64>(),							ZEMTType(ZEMT_BT_INTEGER_64, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEUInt8>,							ZEArray<ZEUInt8>(),							ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_8, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEUInt16>,							ZEArray<ZEUInt16>(),						ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_16, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEUInt32>,							ZEArray<ZEUInt32>(),						ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_32, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEUInt64>,							ZEArray<ZEUInt64>(),						ZEMTType(ZEMT_BT_UNSIGNED_INTEGER_64, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<float>&,									ZEArray<float>(),							ZEMTType(ZEMT_BT_FLOAT, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, NULL));
ZEMT_TYPE_TEST(ZEArray<double>&,								ZEArray<double>(),							ZEMTType(ZEMT_BT_DOUBLE, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, NULL));
ZEMT_TYPE_TEST(ZEArray<bool>&,									ZEArray<bool>(),							ZEMTType(ZEMT_BT_BOOLEAN, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEString>&,								ZEArray<ZEString>(),						ZEMTType(ZEMT_BT_STRING, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEVector2>&,						ZEArray<ZEVector2>(),						ZEMTType(ZEMT_BT_VECTOR2, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEVector2d>&,						ZEArray<ZEVector2d>(),						ZEMTType(ZEMT_BT_VECTOR2D, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEVector3>&,						ZEArray<ZEVector3>(),						ZEMTType(ZEMT_BT_VECTOR3, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, NULL));
ZEMT_TYPE_TEST(const ZEArray<ZEVector3d>&,						ZEArray<ZEVector3d>(),						ZEMTType(ZEMT_BT_VECTOR3D, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEVector4>,								ZEArray<ZEVector4>(),						ZEMTType(ZEMT_BT_VECTOR4, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEVector4d>,								ZEArray<ZEVector4d>(),						ZEMTType(ZEMT_BT_VECTOR4D, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEQuaternion>,							ZEArray<ZEQuaternion>(),					ZEMTType(ZEMT_BT_QUATERNION, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEMatrix3x3>,							ZEArray<ZEMatrix3x3>(),						ZEMTType(ZEMT_BT_MATRIX3X3, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEMatrix3x3d>,							ZEArray<ZEMatrix3x3d>(),					ZEMTType(ZEMT_BT_MATRIX3X3D, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEMatrix4x4>,							ZEArray<ZEMatrix4x4>(),						ZEMTType(ZEMT_BT_MATRIX4X4, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZEMatrix4x4d>,							ZEArray<ZEMatrix4x4d>(),					ZEMTType(ZEMT_BT_MATRIX4X4D, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, NULL));
ZEMT_TYPE_TEST(ZEArray<ZETestObject>,							ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZETestObject>,						ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZETestObject>&,							ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZETestObject>&,					ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZETestObject*>,							ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<const ZETestObject*>,					ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZETestObject*>,					ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<const ZETestObject*>,				ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZETestObject*>&,							ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<const ZETestObject*>&,					ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZETestObject*>&,					ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<const ZETestObject*>&,				ZEArray<ZETestObject>(),					ZEMTType(ZEMT_BT_OBJECT_PTR, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZEHolder<ZETestObject>>,					ZEArray<ZEHolder<ZETestObject>>(),			ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZEHolder<const ZETestObject>>,			ZEArray<ZEHolder<const ZETestObject>>(),	ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZEHolder<ZETestObject>>,			ZEArray<ZEHolder<ZETestObject>>(),			ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZEHolder<const ZETestObject>>,		ZEArray<ZEHolder<const ZETestObject>>(),	ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_VALUE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZEHolder<ZETestObject>>&,				ZEArray<ZEHolder<ZETestObject>>(),			ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(ZEArray<ZEHolder<const ZETestObject>>&,			ZEArray<ZEHolder<const ZETestObject>>(),	ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZEHolder<ZETestObject>>&,			ZEArray<ZEHolder<ZETestObject>>(),			ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, ZETestObject::Class()));
ZEMT_TYPE_TEST(const ZEArray<ZEHolder<const ZETestObject>>&,	ZEArray<ZEHolder<const ZETestObject>>(),	ZEMTType(ZEMT_BT_OBJECT_HOLDER, ZEMT_TQ_CONST_VALUE, ZEMT_CT_ARRAY, ZEMT_TQ_CONST_REFERENCE, ZETestObject::Class()));

ZEMT_TYPE_TEST_INVALID(ZEString*);
ZEMT_TYPE_TEST_INVALID(const ZEString*);
ZEMT_TYPE_TEST_INVALID(const ZEString**);
ZEMT_TYPE_TEST_INVALID(ZEString* const*);
ZEMT_TYPE_TEST_INVALID(const ZEString* const*);
ZEMT_TYPE_TEST_INVALID(ZETestObject**);
ZEMT_TYPE_TEST_INVALID(const ZETestObject**);
ZEMT_TYPE_TEST_INVALID(ZETestObject* const*);
ZEMT_TYPE_TEST_INVALID(const ZETestObject* const);
ZEMT_TYPE_TEST_INVALID(ZEHolder<ZEInt8>);
ZEMT_TYPE_TEST_INVALID(ZEHolder<ZEUInt32>);
ZEMT_TYPE_TEST_INVALID(ZEHolder<ZEUInt64>);
ZEMT_TYPE_TEST_INVALID(ZEHolder<ZEString>);
ZEMT_TYPE_TEST_INVALID(ZEHolder<ZEMatrix4x4d>);
ZEMT_TYPE_TEST_INVALID(ZEHolder<ZETestObject>*);
ZEMT_TYPE_TEST_INVALID(ZEHolder<const ZETestObject>*);
ZEMT_TYPE_TEST_INVALID(const ZEHolder<ZETestObject>*);
ZEMT_TYPE_TEST_INVALID(const ZEHolder<const ZETestObject>*);
ZEMT_TYPE_TEST_INVALID(const ZEHolder<ZETestObject>);
ZEMT_TYPE_TEST_INVALID(const ZEHolder<const ZETestObject>);
ZEMT_TYPE_TEST_INVALID(const ZEHolder<ZETestObject>&);
ZEMT_TYPE_TEST_INVALID(const ZEHolder<const ZETestObject>&);
ZEMT_TYPE_TEST_INVALID(ZEArray<ZEUInt32*>);
ZEMT_TYPE_TEST_INVALID(ZEArray<ZEString*>);
ZEMT_TYPE_TEST_INVALID(ZEArray<ZEMatrix4x4*>);
ZEMT_TYPE_TEST_INVALID(ZEArray<bool*>);
ZEMT_TYPE_TEST_INVALID(ZEArray<const float*>);
ZEMT_TYPE_TEST_INVALID(ZEArray<const double*>);
