//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEResourceConfiguratorWidget.cpp
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

#include "ZEResourceConfiguratorWidget.h"
#include "ui_ZEResourceConfiguratorWidget.h"

#include "ZEResourceOptionTreeItem.h"
#include "ZEResourceConfigurator.h"

#include "ZEML/ZEMLNode.h"
#include "ZEML/ZEMLProperty.h"
#include "ZEFile/ZEFile.h"
#include "ZEFile/ZEFileCommon.h"

void ZEResourceConfiguratorWidget::TreeItemClicked(QTreeWidgetItem* Item, int Column)
{
	ZEResourceOptionTreeItem* ZEItem = (ZEResourceOptionTreeItem*)Item;
	OptionWidget->setVisible(true);
	OptionWidget->SetOptions(ZEItem->GetResourceOption());
	CurrentSelectedResource = (ZEResourceOptionTreeItem*)Item;
}

void ZEResourceConfiguratorWidget::OptionChanged(ZEResourceOptionWidget* Widget)
{
	CurrentSelectedResource->GetResourceOption()->Action = Widget->GetActionOnAvailable();
	CurrentSelectedResource->GetResourceOption()->IsAutoGenerated = Widget->GetAutoGenerated();
	CurrentSelectedResource->GetResourceOption()->ExportPath = Widget->GetExportPath();
	CurrentSelectedResource->GetResourceOption()->PhysicalPath = Widget->GetPhysicalPath();
	((ZEResourceOptionTreeItem*)CurrentSelectedResource)->Update();
}

ZEResourceConfiguratorWidget::ZEResourceConfiguratorWidget(QWidget* Parent) : QDialog(Parent)
{
	CurrentSelectedResource = NULL;

	Form = new Ui::ZEResourceConfiguratorUI();
	Form->setupUi(this);

	OptionWidget = new ZEResourceOptionWidget(Form->OptionsParentWidget);
	Form->OptionsParentWidgetLayout->addWidget(OptionWidget);
	OptionWidget->setVisible(false);

	this->ConfigurationWidget = ConfigurationWidget;
	connect(Form->ResourcesTreeWidget, SIGNAL(itemClicked(QTreeWidgetItem*, int)), this, SLOT(TreeItemClicked(QTreeWidgetItem*, int)));
	connect(OptionWidget, SIGNAL(OptionChanged(ZEResourceOptionWidget*)), this, SLOT(OptionChanged(ZEResourceOptionWidget*)));
}

ZEResourceConfiguratorWidget::~ZEResourceConfiguratorWidget()
{

}

void ZEResourceConfiguratorWidget::AddResource(const ZEString& Identifier, const ZEString& Type, const ZEString& PhysicalPath, const ZEString& ExportPath, ZEResourceOptionAvailableAction Action, bool IsAutoGenerated)
{
	if (Identifier.GetLength() == 0)
	{
		zeLog("Resource identifier can not be NULL.");
		return;
	}

	zeLog(Identifier.ToCString());
	zeLog(Type.ToCString());

	if (PhysicalPath.GetLength() != 0)
		zeLog(PhysicalPath.ToCString());

	if (!IsAutoGenerated && PhysicalPath.GetLength() == 0)
		zeLog("Non auto generated resource physical path can not be empty.");

	ZEResourceOption* TempOption = NULL;
	
	if (Configurator.GetOption(Identifier, TempOption))
	{
		bool IsFound = false;

		for (ZESize I = 0; I < Form->ResourcesTreeWidget->topLevelItemCount(); I++)
		{
			ZEResourceOption* CurrentResourceOption = static_cast<ZEResourceOptionTreeItem*>(Form->ResourcesTreeWidget->topLevelItem(I))->GetResourceOption();

			if (CurrentResourceOption->Identifier == Identifier)
				IsFound = true;
		}

		if (!IsFound)
		{
			ZEResourceOptionTreeItem* NewItem = new ZEResourceOptionTreeItem();
			NewItem->SetResourceOption(TempOption);
			Form->ResourcesTreeWidget->addTopLevelItem(NewItem);
			NewItem->Update();
		}
		else
			return;
	}
	else
	{
		ZEResourceOptionTreeItem* NewItem = new ZEResourceOptionTreeItem();

		if (ExportPath.GetLength() != 0)
			Configurator.AddResource(Identifier, Type, ExportPath, PhysicalPath, Action, IsAutoGenerated);
		else
			Configurator.AddResource(Identifier, Type, DefaultExportPath, PhysicalPath, Action, IsAutoGenerated);

		Configurator.GetOption(Identifier, TempOption);
		NewItem->SetResourceOption(TempOption);
		Form->ResourcesTreeWidget->addTopLevelItem(NewItem);
		NewItem->Update();
	}
}

void ZEResourceConfiguratorWidget::AddResource(const ZEString& Identifier, const ZEString& Type, const ZEString& ExportPath, ZEResourceOptionAvailableAction Action, bool IsAutoGenerated)
{
	AddResource(Identifier , Type, ZEString(), ExportPath, Action, IsAutoGenerated);
}

const ZEArray<ZEResourceOption*>& ZEResourceConfiguratorWidget::GetOptions()
{
	return Configurator.GetOptions();
}

void ZEResourceConfiguratorWidget::LoadPreset(const ZEString& Path)
{
	ZEFile File;
	
	if (!File.Open(Path, ZE_FOM_READ, ZE_FCM_NONE))
		zeWarning("Preset file not found.");
	else
	{
		Configurator.LoadPresetFromFile(&File);
		File.Close();
	}
}

void ZEResourceConfiguratorWidget::SavePreset(const ZEString& Path)
{
	ZEFile File;
	if (!File.Open(Path, ZE_FOM_READ_WRITE, ZE_FCM_OVERWRITE))
	{
		zeError("Can not open given file to write. File path : %s", Path.ToCString());
		return;
	}

	Configurator.SavePresetToFile(&File);
	
	if (File.IsOpen())
		File.Close();
}

bool ZEResourceConfiguratorWidget::GetOption(const ZEString& Identifier, ZEResourceOption& Option)
{
	ZEResourceOption* TempOption;
	bool Result = Configurator.GetOption(Identifier, TempOption);
	
	if (Result)
	{
		Option = *TempOption;
		return true;
	}
	else
		return false;	 
}

void ZEResourceConfiguratorWidget::SetZEWorkingDir(const ZEString& Path)
{
	ZinekDirectory = Path;
}

bool ZEResourceConfiguratorWidget::GetCopyState(const ZEString& Identifier)
{
	return Configurator.GetResourceCopyState(Identifier);
}

ZEString ZEResourceConfiguratorWidget::GetResourceRelativePath(ZEString& RelativeTo, const ZEString& Identifier)
{
	return Configurator.GetResourceRelativePath(RelativeTo, Identifier);
}

void ZEResourceConfiguratorWidget::SetDefaultExportPath(ZEString Path)
{
	DefaultExportPath = Path;
}
