//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEResourceConfigurationWidget.cpp
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

#include "ZEResourceConfigurationWidget.h"
#include "ui_ZEResourceConfigurationWidget.h"
#include "ZEResourceOptionTreeItem.h"
#include "QtGui/QTreeWidgetItem"
#include "ZEResourceOption.h"
#include "ZEML/ZEMLNode.h"
#include "ZEFile/ZEFile.h"
#include "ZEML/ZEMLProperty.h"
#include "ZEResourceConfigurationWidgetQt.h"
#include "ZEFile/ZEFileUtils.h"

#include <time.h>
#include "ZEFile/ZEPathUtils.h"

inline static time_t GetTime(ZEFileTime* Date)
{
	struct tm CDate;
	memset(&CDate, 0, sizeof(struct tm));

	CDate.tm_year = Date->Year - 1900;
	CDate.tm_mon = Date->Month;
	CDate.tm_mday = Date->Day;
	CDate.tm_hour = Date->Hour;
	CDate.tm_min = Date->Minute;
	CDate.tm_sec = Date->Second;

	return mktime(&CDate);
}

ZEResourceConfigurationWidget::ZEResourceConfigurationWidget(QWidget* Parent)
{
	Preset = NULL;
	QtComponents = new ZEResourceConfigurationWidgetQt(this, Parent);
}

ZEResourceConfigurationWidget::~ZEResourceConfigurationWidget()
{
	delete QtComponents;

// 	if(Preset != NULL)
// 		delete Preset;

	for (ZESize I = 0; I < ResourceOptions.GetCount(); I++)
	{
		delete ResourceOptions[I];
		ResourceOptions[I] = NULL;
	}
}

void ZEResourceConfigurationWidget::AddResource(const ZEString& Identifier, const ZEString& PhysicalPath, const ZEString& ExportPath, ZEResourceOptionAvailableAction Action, bool IsAutoGenerated)
{
	ZEArray<ZEMLNode*> SubNodes;

	if(Preset != NULL)
		SubNodes = Preset->GetSubNodes(Identifier);

	ZEResourceOption* NewOption = new ZEResourceOption();
	ResourceOptions.Add(NewOption);
	ZEResourceOptionTreeItem* NewItem = new ZEResourceOptionTreeItem();

	ResourceOptions.GetLastItem()->Identifier = Identifier;

	if(SubNodes.GetCount() == 0)
	{
		ResourceOptions.GetLastItem()->PhysicalPath = PhysicalPath;
		ResourceOptions.GetLastItem()->ExportPath = ExportPath;
		ResourceOptions.GetLastItem()->Action = Action;
		ResourceOptions.GetLastItem()->IsAutoGenerated = IsAutoGenerated;
	}
	else if(SubNodes.GetCount() > 0)
	{
		if(SubNodes.GetCount() != 1)
			zeWarning("Duplicate resource identifier found.");

		for (ZESize I = 0; I < SubNodes[0]->GetProperties().GetCount(); I++)
		{
			if(SubNodes[0]->GetProperties()[I]->GetName() == ZEString("ExportPath"))
				ResourceOptions.GetLastItem()->ExportPath = ((ZEMLProperty*)(SubNodes[0]->GetProperties()[I]))->GetValue().GetString();

			else if(SubNodes[0]->GetProperties()[I]->GetName() == ZEString("PhysicalPath"))
				ResourceOptions.GetLastItem()->PhysicalPath = ((ZEMLProperty*)(SubNodes[0]->GetProperties()[I]))->GetValue().GetString();

			else if(SubNodes[0]->GetProperties()[I]->GetName() == ZEString("Action"))
				ResourceOptions.GetLastItem()->Action = (ZEResourceOptionAvailableAction)((ZEMLProperty*)(SubNodes[0]->GetProperties()[I]))->GetValue().GetInt32();

			else if(SubNodes[0]->GetProperties()[I]->GetName() == ZEString("IsAutoGenerated"))
				ResourceOptions.GetLastItem()->IsAutoGenerated = ((ZEMLProperty*)(SubNodes[0]->GetProperties()[I]))->GetValue().GetBoolean();
		}
	}

	NewItem->SetResourceOption(ResourceOptions[ResourceOptions.GetCount() - 1]);
	QtComponents->Form->ResourcesTreeWidget->addTopLevelItem(NewItem);
	NewItem->Update();
}

void ZEResourceConfigurationWidget::AddResource(const ZEString& Identifier, const ZEString& ExportPath, ZEResourceOptionAvailableAction Action, bool IsAutoGenerated)
{
	AddResource(Identifier ,ZEString(), ExportPath, Action, IsAutoGenerated);
}

bool ZEResourceConfigurationWidget::Show()
{
	if(QtComponents->Dialog->exec() == QDialog::Accepted)
		return true;
	else
		return false;
}

void ZEResourceConfigurationWidget::Hide()
{
	QtComponents->Dialog->close();
}

const ZEArray<ZEResourceOption*>& ZEResourceConfigurationWidget::GetOptions()
{
	return ResourceOptions;
}

void ZEResourceConfigurationWidget::SetPresetFilePath(const ZEString& Path)
{
	if(Preset != NULL)
	{
		delete Preset;
		Preset = NULL;
	}

	ZEFile PresetFile;
	
	if(!PresetFile.Open(Path, ZE_FOM_READ, ZE_FCM_NONE))
		zeWarning("Preset file not found.");
	else
	{
		Preset = new ZEMLNode("Preset");
		Preset->Read(&PresetFile);
		PresetFile.Close();
	}
}

void ZEResourceConfigurationWidget::SavePresets(const ZEString& Path)
{
	ZEFile PresetFile;

	if(!PresetFile.Open(Path, ZE_FOM_READ_WRITE, ZE_FCM_OVERWRITE))
		zeError("Cannot open preset file for saving presets %s.", Path);
	else
	{
		if(Preset != NULL)
		{
			delete Preset;
			Preset = NULL;
		}
		
		if(Preset == NULL)
			Preset = new ZEMLNode("Preset");

		for(ZESize I = 0; I < ResourceOptions.GetCount(); I++)
		{
			ZEMLNode* Node = Preset->AddSubNode(ResourceOptions[I]->Identifier);
			Node->AddProperty("ExportPath", ResourceOptions[I]->ExportPath);
			Node->AddProperty("PhysicalPath", ResourceOptions[I]->PhysicalPath);
			Node->AddProperty("Action", ResourceOptions[I]->Action);
			Node->AddProperty("IsAutoGenerated", ResourceOptions[I]->IsAutoGenerated);
		}

		Preset->Write(&PresetFile);
		PresetFile.Close();
	}
}

const bool ZEResourceConfigurationWidget::GetOption(const ZEString& Identifier, ZEResourceOption& Option)
{
	for (ZESize I = 0; I < ResourceOptions.GetCount(); I++)
	{
		if(ResourceOptions[I]->Identifier == Identifier)
		{
			Option.Action = ResourceOptions[I]->Action;
			Option.ExportPath = ResourceOptions[I]->ExportPath;
			Option.PhysicalPath = ResourceOptions[I]->PhysicalPath;
			Option.IsAutoGenerated = ResourceOptions[I]->IsAutoGenerated;
			Option.Identifier = ResourceOptions[I]->Identifier;
			return true;
		}
	}

	return false;
}

void ZEResourceConfigurationWidget::SetZEWorkingDir(const ZEString& Path)
{
	ZEDir = Path;
}

bool ZEResourceConfigurationWidget::GetCopyState(const ZEString& Identifier)
{
	ZEResourceOption TempOption;
	bool IsAvailableAtExportLocation = false;

	if(!GetOption(Identifier, TempOption))
	{
		zeError("Resource option not found. Resource identifier : %s", Identifier.ToCString());
		return false;
	}

	if(ZEFileUtils::IsFile(TempOption.ExportPath + ZEPathUtils::GetSeperator() + TempOption.Identifier))
		IsAvailableAtExportLocation = true;

	if(TempOption.Action == ZE_ROAA_DO_NOTHING)
	{
		return false;
	}
	else if(TempOption.Action == ZE_ROAA_COPY_OVERWRITE)
	{
		return true;
	}
	else if(TempOption.Action == ZE_ROAA_COPY_IF_NEWER)
	{
		if(TempOption.IsAutoGenerated)
			return true;
		else
		{
			if(!IsAvailableAtExportLocation)
				return true;

			ZEFileTime* ExportedFileTime = new ZEFileTime();
			ZEFileTime* SourceFileTime = new ZEFileTime();
			ZEFileUtils::GetModificationTime(ExportedFileTime, TempOption.ExportPath + "\\" + TempOption.Identifier);
			ZEFileUtils::GetModificationTime(SourceFileTime, TempOption.PhysicalPath);

			if(GetTime(ExportedFileTime) >= GetTime(SourceFileTime))
				return true;

			return false;
		}
	}
}

ZEString ZEResourceConfigurationWidget::GetResourceRelativePath(ZEString& RelativeTo, const ZEString& Identifier)
{
	ZEResourceOption Option;
	GetOption(Identifier, Option);

	return ZEPathUtils::GetRelativePath(RelativeTo, Option.ExportPath + ZEPathUtils::GetSeperator() + Identifier);
}
