//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEMacroRepeater.h
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

#pragma once
#ifndef __ZE_MACRO_REPEATER_H__
#define __ZE_MACRO_REPEATER_H__

#define ZE_MACRO_REPEATER(Count, Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL(Count, Macro, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL(Count, Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_##Count(Macro, Parameter)

#define ZE_MACRO_REPEATER_INTERNAL_0(Macro, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_1(Macro, Parameter) Macro(0, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_2(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_1(Macro, Parameter) Macro(1, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_3(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_2(Macro, Parameter) Macro(2, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_4(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_3(Macro, Parameter) Macro(3, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_5(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_4(Macro, Parameter) Macro(4, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_6(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_5(Macro, Parameter) Macro(5, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_7(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_6(Macro, Parameter) Macro(6, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_8(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_7(Macro, Parameter) Macro(7, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_9(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_8(Macro, Parameter) Macro(8, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_10(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_9(Macro, Parameter) Macro(9, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_11(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_10(Macro, Parameter) Macro(10, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_12(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_11(Macro, Parameter) Macro(11, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_13(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_12(Macro, Parameter) Macro(12, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_14(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_13(Macro, Parameter) Macro(13, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_15(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_14(Macro, Parameter) Macro(14, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_16(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_15(Macro, Parameter) Macro(15, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_17(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_16(Macro, Parameter) Macro(16, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_18(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_17(Macro, Parameter) Macro(17, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_19(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_18(Macro, Parameter) Macro(18, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_20(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_19(Macro, Parameter) Macro(19, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_21(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_20(Macro, Parameter) Macro(20, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_22(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_21(Macro, Parameter) Macro(21, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_23(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_22(Macro, Parameter) Macro(22, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_24(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_23(Macro, Parameter) Macro(23, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_25(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_24(Macro, Parameter) Macro(24, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_26(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_25(Macro, Parameter) Macro(25, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_27(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_26(Macro, Parameter) Macro(26, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_28(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_27(Macro, Parameter) Macro(27, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_29(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_28(Macro, Parameter) Macro(28, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_30(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_29(Macro, Parameter) Macro(29, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_31(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_30(Macro, Parameter) Macro(30, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_32(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_31(Macro, Parameter) Macro(31, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_33(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_32(Macro, Parameter) Macro(32, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_34(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_33(Macro, Parameter) Macro(33, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_35(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_34(Macro, Parameter) Macro(34, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_36(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_35(Macro, Parameter) Macro(35, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_37(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_36(Macro, Parameter) Macro(36, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_38(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_37(Macro, Parameter) Macro(37, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_39(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_38(Macro, Parameter) Macro(38, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_40(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_39(Macro, Parameter) Macro(39, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_41(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_40(Macro, Parameter) Macro(40, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_42(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_41(Macro, Parameter) Macro(41, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_43(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_42(Macro, Parameter) Macro(42, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_44(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_43(Macro, Parameter) Macro(43, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_45(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_44(Macro, Parameter) Macro(44, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_46(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_45(Macro, Parameter) Macro(45, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_47(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_46(Macro, Parameter) Macro(46, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_48(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_47(Macro, Parameter) Macro(47, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_49(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_48(Macro, Parameter) Macro(48, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_50(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_49(Macro, Parameter) Macro(49, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_51(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_50(Macro, Parameter) Macro(50, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_52(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_51(Macro, Parameter) Macro(51, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_53(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_52(Macro, Parameter) Macro(52, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_54(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_53(Macro, Parameter) Macro(53, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_55(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_54(Macro, Parameter) Macro(54, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_56(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_55(Macro, Parameter) Macro(55, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_57(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_56(Macro, Parameter) Macro(56, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_58(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_57(Macro, Parameter) Macro(57, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_59(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_58(Macro, Parameter) Macro(58, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_60(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_59(Macro, Parameter) Macro(59, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_61(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_60(Macro, Parameter) Macro(60, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_62(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_61(Macro, Parameter) Macro(61, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_63(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_62(Macro, Parameter) Macro(62, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_64(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_63(Macro, Parameter) Macro(63, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_65(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_64(Macro, Parameter) Macro(64, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_66(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_65(Macro, Parameter) Macro(65, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_67(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_66(Macro, Parameter) Macro(66, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_68(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_67(Macro, Parameter) Macro(67, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_69(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_68(Macro, Parameter) Macro(68, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_70(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_69(Macro, Parameter) Macro(69, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_71(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_70(Macro, Parameter) Macro(70, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_72(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_71(Macro, Parameter) Macro(71, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_73(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_72(Macro, Parameter) Macro(72, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_74(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_73(Macro, Parameter) Macro(73, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_75(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_74(Macro, Parameter) Macro(74, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_76(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_75(Macro, Parameter) Macro(75, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_77(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_76(Macro, Parameter) Macro(76, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_78(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_77(Macro, Parameter) Macro(77, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_79(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_78(Macro, Parameter) Macro(78, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_80(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_79(Macro, Parameter) Macro(79, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_81(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_80(Macro, Parameter) Macro(80, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_82(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_81(Macro, Parameter) Macro(81, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_83(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_82(Macro, Parameter) Macro(82, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_84(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_83(Macro, Parameter) Macro(83, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_85(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_84(Macro, Parameter) Macro(84, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_86(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_85(Macro, Parameter) Macro(85, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_87(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_86(Macro, Parameter) Macro(86, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_88(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_87(Macro, Parameter) Macro(87, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_89(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_88(Macro, Parameter) Macro(88, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_90(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_89(Macro, Parameter) Macro(89, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_91(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_90(Macro, Parameter) Macro(90, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_92(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_91(Macro, Parameter) Macro(91, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_93(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_92(Macro, Parameter) Macro(92, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_94(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_93(Macro, Parameter) Macro(93, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_95(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_94(Macro, Parameter) Macro(94, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_96(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_95(Macro, Parameter) Macro(95, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_97(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_96(Macro, Parameter) Macro(96, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_98(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_97(Macro, Parameter) Macro(97, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_99(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_98(Macro, Parameter) Macro(98, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_100(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_99(Macro, Parameter) Macro(99, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_101(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_100(Macro, Parameter) Macro(100, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_102(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_101(Macro, Parameter) Macro(101, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_103(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_102(Macro, Parameter) Macro(102, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_104(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_103(Macro, Parameter) Macro(103, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_105(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_104(Macro, Parameter) Macro(104, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_106(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_105(Macro, Parameter) Macro(105, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_107(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_106(Macro, Parameter) Macro(106, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_108(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_107(Macro, Parameter) Macro(107, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_109(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_108(Macro, Parameter) Macro(108, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_110(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_109(Macro, Parameter) Macro(109, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_111(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_110(Macro, Parameter) Macro(110, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_112(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_111(Macro, Parameter) Macro(111, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_113(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_112(Macro, Parameter) Macro(112, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_114(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_113(Macro, Parameter) Macro(113, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_115(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_114(Macro, Parameter) Macro(114, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_116(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_115(Macro, Parameter) Macro(115, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_117(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_116(Macro, Parameter) Macro(116, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_118(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_117(Macro, Parameter) Macro(117, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_119(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_118(Macro, Parameter) Macro(118, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_120(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_119(Macro, Parameter) Macro(119, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_121(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_120(Macro, Parameter) Macro(120, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_122(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_121(Macro, Parameter) Macro(121, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_123(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_122(Macro, Parameter) Macro(122, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_124(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_123(Macro, Parameter) Macro(123, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_125(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_124(Macro, Parameter) Macro(124, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_126(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_125(Macro, Parameter) Macro(125, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_127(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_126(Macro, Parameter) Macro(126, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_128(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_127(Macro, Parameter) Macro(127, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_129(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_128(Macro, Parameter) Macro(128, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_130(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_129(Macro, Parameter) Macro(129, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_131(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_130(Macro, Parameter) Macro(130, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_132(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_131(Macro, Parameter) Macro(131, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_133(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_132(Macro, Parameter) Macro(132, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_134(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_133(Macro, Parameter) Macro(133, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_135(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_134(Macro, Parameter) Macro(134, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_136(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_135(Macro, Parameter) Macro(135, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_137(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_136(Macro, Parameter) Macro(136, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_138(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_137(Macro, Parameter) Macro(137, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_139(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_138(Macro, Parameter) Macro(138, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_140(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_139(Macro, Parameter) Macro(139, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_141(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_140(Macro, Parameter) Macro(140, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_142(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_141(Macro, Parameter) Macro(141, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_143(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_142(Macro, Parameter) Macro(142, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_144(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_143(Macro, Parameter) Macro(143, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_145(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_144(Macro, Parameter) Macro(144, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_146(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_145(Macro, Parameter) Macro(145, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_147(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_146(Macro, Parameter) Macro(146, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_148(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_147(Macro, Parameter) Macro(147, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_149(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_148(Macro, Parameter) Macro(148, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_150(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_149(Macro, Parameter) Macro(149, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_151(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_150(Macro, Parameter) Macro(150, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_152(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_151(Macro, Parameter) Macro(151, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_153(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_152(Macro, Parameter) Macro(152, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_154(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_153(Macro, Parameter) Macro(153, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_155(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_154(Macro, Parameter) Macro(154, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_156(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_155(Macro, Parameter) Macro(155, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_157(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_156(Macro, Parameter) Macro(156, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_158(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_157(Macro, Parameter) Macro(157, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_159(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_158(Macro, Parameter) Macro(158, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_160(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_159(Macro, Parameter) Macro(159, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_161(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_160(Macro, Parameter) Macro(160, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_162(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_161(Macro, Parameter) Macro(161, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_163(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_162(Macro, Parameter) Macro(162, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_164(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_163(Macro, Parameter) Macro(163, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_165(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_164(Macro, Parameter) Macro(164, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_166(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_165(Macro, Parameter) Macro(165, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_167(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_166(Macro, Parameter) Macro(166, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_168(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_167(Macro, Parameter) Macro(167, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_169(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_168(Macro, Parameter) Macro(168, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_170(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_169(Macro, Parameter) Macro(169, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_171(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_170(Macro, Parameter) Macro(170, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_172(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_171(Macro, Parameter) Macro(171, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_173(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_172(Macro, Parameter) Macro(172, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_174(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_173(Macro, Parameter) Macro(173, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_175(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_174(Macro, Parameter) Macro(174, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_176(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_175(Macro, Parameter) Macro(175, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_177(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_176(Macro, Parameter) Macro(176, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_178(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_177(Macro, Parameter) Macro(177, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_179(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_178(Macro, Parameter) Macro(178, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_180(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_179(Macro, Parameter) Macro(179, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_181(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_180(Macro, Parameter) Macro(180, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_182(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_181(Macro, Parameter) Macro(181, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_183(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_182(Macro, Parameter) Macro(182, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_184(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_183(Macro, Parameter) Macro(183, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_185(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_184(Macro, Parameter) Macro(184, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_186(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_185(Macro, Parameter) Macro(185, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_187(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_186(Macro, Parameter) Macro(186, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_188(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_187(Macro, Parameter) Macro(187, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_189(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_188(Macro, Parameter) Macro(188, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_190(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_189(Macro, Parameter) Macro(189, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_191(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_190(Macro, Parameter) Macro(190, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_192(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_191(Macro, Parameter) Macro(191, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_193(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_192(Macro, Parameter) Macro(192, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_194(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_193(Macro, Parameter) Macro(193, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_195(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_194(Macro, Parameter) Macro(194, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_196(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_195(Macro, Parameter) Macro(195, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_197(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_196(Macro, Parameter) Macro(196, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_198(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_197(Macro, Parameter) Macro(197, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_199(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_198(Macro, Parameter) Macro(198, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_200(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_199(Macro, Parameter) Macro(199, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_201(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_200(Macro, Parameter) Macro(200, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_202(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_201(Macro, Parameter) Macro(201, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_203(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_202(Macro, Parameter) Macro(202, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_204(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_203(Macro, Parameter) Macro(203, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_205(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_204(Macro, Parameter) Macro(204, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_206(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_205(Macro, Parameter) Macro(205, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_207(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_206(Macro, Parameter) Macro(206, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_208(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_207(Macro, Parameter) Macro(207, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_209(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_208(Macro, Parameter) Macro(208, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_210(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_209(Macro, Parameter) Macro(209, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_211(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_210(Macro, Parameter) Macro(210, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_212(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_211(Macro, Parameter) Macro(211, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_213(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_212(Macro, Parameter) Macro(212, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_214(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_213(Macro, Parameter) Macro(213, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_215(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_214(Macro, Parameter) Macro(214, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_216(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_215(Macro, Parameter) Macro(215, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_217(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_216(Macro, Parameter) Macro(216, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_218(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_217(Macro, Parameter) Macro(217, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_219(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_218(Macro, Parameter) Macro(218, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_220(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_219(Macro, Parameter) Macro(219, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_221(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_220(Macro, Parameter) Macro(220, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_222(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_221(Macro, Parameter) Macro(221, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_223(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_222(Macro, Parameter) Macro(222, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_224(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_223(Macro, Parameter) Macro(223, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_225(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_224(Macro, Parameter) Macro(224, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_226(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_225(Macro, Parameter) Macro(225, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_227(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_226(Macro, Parameter) Macro(226, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_228(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_227(Macro, Parameter) Macro(227, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_229(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_228(Macro, Parameter) Macro(228, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_230(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_229(Macro, Parameter) Macro(229, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_231(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_230(Macro, Parameter) Macro(230, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_232(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_231(Macro, Parameter) Macro(231, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_233(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_232(Macro, Parameter) Macro(232, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_234(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_233(Macro, Parameter) Macro(233, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_235(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_234(Macro, Parameter) Macro(234, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_236(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_235(Macro, Parameter) Macro(235, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_237(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_236(Macro, Parameter) Macro(236, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_238(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_237(Macro, Parameter) Macro(237, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_239(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_238(Macro, Parameter) Macro(238, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_240(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_239(Macro, Parameter) Macro(239, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_241(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_240(Macro, Parameter) Macro(240, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_242(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_241(Macro, Parameter) Macro(241, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_243(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_242(Macro, Parameter) Macro(242, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_244(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_243(Macro, Parameter) Macro(243, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_245(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_244(Macro, Parameter) Macro(244, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_246(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_245(Macro, Parameter) Macro(245, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_247(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_246(Macro, Parameter) Macro(246, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_248(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_247(Macro, Parameter) Macro(247, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_249(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_248(Macro, Parameter) Macro(248, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_250(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_249(Macro, Parameter) Macro(249, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_251(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_250(Macro, Parameter) Macro(250, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_252(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_251(Macro, Parameter) Macro(251, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_253(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_252(Macro, Parameter) Macro(252, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_254(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_253(Macro, Parameter) Macro(253, Parameter)
#define ZE_MACRO_REPEATER_INTERNAL_255(Macro, Parameter) ZE_MACRO_REPEATER_INTERNAL_(Macro, Parameter) Macro(254, Parameter)

#endif
