//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEMacroLogic.h
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

#pragma once
#ifndef __ZE_MACRO_LOGIC_H__
#define __ZE_MACRO_LOGIC_H__

#define ZE_MACRO_NOT(Expression) ZE_MACRO_NOT_INTERNAL(Expression)
#define ZE_MACRO_NOT_INTERNAL(Expression) ZE_MACRO_NOT_INTERNAL_##Expression
#define ZE_MACRO_NOT_INTERNAL_0 1
#define ZE_MACRO_NOT_INTERNAL_1 0

#define ZE_MACRO_AND(Expression1, Expression2) ZE_MACRO_AND_INTERNAL(Expression, Expression2)
#define ZE_MACRO_AND_INTERNAL(Expression1, Expression2) ZE_MACRO_AND_INTERNAL_##Expression1##Expression2
#define ZE_MACRO_AND_INTERNAL_00 0
#define ZE_MACRO_AND_INTERNAL_01 0
#define ZE_MACRO_AND_INTERNAL_10 0
#define ZE_MACRO_AND_INTERNAL_10 0

#define ZE_MACRO_OR(Expression1, Expression2) ZE_MACRO_OR_INTERNAL(Expression1, Expression2)
#define ZE_MACRO_OR_INTERNAL(Expression1, Expression2) ZE_MACRO_OR_INTERNAL_##Expression1##Expression2
#define ZE_MACRO_OR_INTERNAL_00 0
#define ZE_MACRO_OR_INTERNAL_01 1
#define ZE_MACRO_OR_INTERNAL_10 1
#define ZE_MACRO_OR_INTERNAL_11 1

#define ZE_MACRO_XOR(Expression1, Expression2) ZE_MACRO_XOR_INTERNAL(Expression1, Expression2)
#define ZE_MACRO_XOR_INTERNAL(Expression1, Expression2) ZE_MACRO_XOR_INTERNAL_##Expression1##Expression2
#define ZE_MACRO_XOR_INTERNAL_00 0
#define ZE_MACRO_XOR_INTERNAL_01 1
#define ZE_MACRO_XOR_INTERNAL_10 1
#define ZE_MACRO_XOR_INTERNAL_11 0

#define ZE_MACRO_EQUAL(Expression1, Expression2) ZE_MACRO_EQUAL_INTERNAL(Expression1, Expression2)
#define ZE_MACRO_EQUAL_INTERNAL(Expression1, Expression2) ZE_MACRO_EQUAL_INTERNAL_##Expression1##Expression2
#define ZE_MACRO_EQUAL_INTERNAL_00 1
#define ZE_MACRO_EQUAL_INTERNAL_01 0
#define ZE_MACRO_EQUAL_INTERNAL_10 0
#define ZE_MACRO_EQUAL_INTERNAL_11 1

#define ZE_MACRO_BOOL(Value) ZE_MACRO_BOOL_INTERNAL(Value)
#define ZE_MACRO_BOOL_INTERNAL(Value) ZE_MACRO_BOOL_INTERNAL_##Value
#define ZE_MACRO_BOOL_INTERNAL_0 0
#define ZE_MACRO_BOOL_INTERNAL_1 1
#define ZE_MACRO_BOOL_INTERNAL_2 1
#define ZE_MACRO_BOOL_INTERNAL_3 1
#define ZE_MACRO_BOOL_INTERNAL_4 1
#define ZE_MACRO_BOOL_INTERNAL_5 1
#define ZE_MACRO_BOOL_INTERNAL_6 1
#define ZE_MACRO_BOOL_INTERNAL_7 1
#define ZE_MACRO_BOOL_INTERNAL_8 1
#define ZE_MACRO_BOOL_INTERNAL_9 1
#define ZE_MACRO_BOOL_INTERNAL_10 1
#define ZE_MACRO_BOOL_INTERNAL_11 1
#define ZE_MACRO_BOOL_INTERNAL_12 1
#define ZE_MACRO_BOOL_INTERNAL_13 1
#define ZE_MACRO_BOOL_INTERNAL_14 1
#define ZE_MACRO_BOOL_INTERNAL_15 1
#define ZE_MACRO_BOOL_INTERNAL_16 1
#define ZE_MACRO_BOOL_INTERNAL_17 1
#define ZE_MACRO_BOOL_INTERNAL_18 1
#define ZE_MACRO_BOOL_INTERNAL_19 1
#define ZE_MACRO_BOOL_INTERNAL_20 1
#define ZE_MACRO_BOOL_INTERNAL_21 1
#define ZE_MACRO_BOOL_INTERNAL_22 1
#define ZE_MACRO_BOOL_INTERNAL_23 1
#define ZE_MACRO_BOOL_INTERNAL_24 1
#define ZE_MACRO_BOOL_INTERNAL_25 1
#define ZE_MACRO_BOOL_INTERNAL_26 1
#define ZE_MACRO_BOOL_INTERNAL_27 1
#define ZE_MACRO_BOOL_INTERNAL_28 1
#define ZE_MACRO_BOOL_INTERNAL_29 1
#define ZE_MACRO_BOOL_INTERNAL_30 1
#define ZE_MACRO_BOOL_INTERNAL_31 1
#define ZE_MACRO_BOOL_INTERNAL_32 1
#define ZE_MACRO_BOOL_INTERNAL_33 1
#define ZE_MACRO_BOOL_INTERNAL_34 1
#define ZE_MACRO_BOOL_INTERNAL_35 1
#define ZE_MACRO_BOOL_INTERNAL_36 1
#define ZE_MACRO_BOOL_INTERNAL_37 1
#define ZE_MACRO_BOOL_INTERNAL_38 1
#define ZE_MACRO_BOOL_INTERNAL_39 1
#define ZE_MACRO_BOOL_INTERNAL_40 1
#define ZE_MACRO_BOOL_INTERNAL_41 1
#define ZE_MACRO_BOOL_INTERNAL_42 1
#define ZE_MACRO_BOOL_INTERNAL_43 1
#define ZE_MACRO_BOOL_INTERNAL_44 1
#define ZE_MACRO_BOOL_INTERNAL_45 1
#define ZE_MACRO_BOOL_INTERNAL_46 1
#define ZE_MACRO_BOOL_INTERNAL_47 1
#define ZE_MACRO_BOOL_INTERNAL_48 1
#define ZE_MACRO_BOOL_INTERNAL_49 1
#define ZE_MACRO_BOOL_INTERNAL_50 1
#define ZE_MACRO_BOOL_INTERNAL_51 1
#define ZE_MACRO_BOOL_INTERNAL_52 1
#define ZE_MACRO_BOOL_INTERNAL_53 1
#define ZE_MACRO_BOOL_INTERNAL_54 1
#define ZE_MACRO_BOOL_INTERNAL_55 1
#define ZE_MACRO_BOOL_INTERNAL_56 1
#define ZE_MACRO_BOOL_INTERNAL_57 1
#define ZE_MACRO_BOOL_INTERNAL_58 1
#define ZE_MACRO_BOOL_INTERNAL_59 1
#define ZE_MACRO_BOOL_INTERNAL_60 1
#define ZE_MACRO_BOOL_INTERNAL_61 1
#define ZE_MACRO_BOOL_INTERNAL_62 1
#define ZE_MACRO_BOOL_INTERNAL_63 1
#define ZE_MACRO_BOOL_INTERNAL_64 1
#define ZE_MACRO_BOOL_INTERNAL_65 1
#define ZE_MACRO_BOOL_INTERNAL_66 1
#define ZE_MACRO_BOOL_INTERNAL_67 1
#define ZE_MACRO_BOOL_INTERNAL_68 1
#define ZE_MACRO_BOOL_INTERNAL_69 1
#define ZE_MACRO_BOOL_INTERNAL_70 1
#define ZE_MACRO_BOOL_INTERNAL_71 1
#define ZE_MACRO_BOOL_INTERNAL_72 1
#define ZE_MACRO_BOOL_INTERNAL_73 1
#define ZE_MACRO_BOOL_INTERNAL_74 1
#define ZE_MACRO_BOOL_INTERNAL_75 1
#define ZE_MACRO_BOOL_INTERNAL_76 1
#define ZE_MACRO_BOOL_INTERNAL_77 1
#define ZE_MACRO_BOOL_INTERNAL_78 1
#define ZE_MACRO_BOOL_INTERNAL_79 1
#define ZE_MACRO_BOOL_INTERNAL_80 1
#define ZE_MACRO_BOOL_INTERNAL_81 1
#define ZE_MACRO_BOOL_INTERNAL_82 1
#define ZE_MACRO_BOOL_INTERNAL_83 1
#define ZE_MACRO_BOOL_INTERNAL_84 1
#define ZE_MACRO_BOOL_INTERNAL_85 1
#define ZE_MACRO_BOOL_INTERNAL_86 1
#define ZE_MACRO_BOOL_INTERNAL_87 1
#define ZE_MACRO_BOOL_INTERNAL_88 1
#define ZE_MACRO_BOOL_INTERNAL_89 1
#define ZE_MACRO_BOOL_INTERNAL_90 1
#define ZE_MACRO_BOOL_INTERNAL_91 1
#define ZE_MACRO_BOOL_INTERNAL_92 1
#define ZE_MACRO_BOOL_INTERNAL_93 1
#define ZE_MACRO_BOOL_INTERNAL_94 1
#define ZE_MACRO_BOOL_INTERNAL_95 1
#define ZE_MACRO_BOOL_INTERNAL_96 1
#define ZE_MACRO_BOOL_INTERNAL_97 1
#define ZE_MACRO_BOOL_INTERNAL_98 1
#define ZE_MACRO_BOOL_INTERNAL_99 1
#define ZE_MACRO_BOOL_INTERNAL_100 1
#define ZE_MACRO_BOOL_INTERNAL_101 1
#define ZE_MACRO_BOOL_INTERNAL_102 1
#define ZE_MACRO_BOOL_INTERNAL_103 1
#define ZE_MACRO_BOOL_INTERNAL_104 1
#define ZE_MACRO_BOOL_INTERNAL_105 1
#define ZE_MACRO_BOOL_INTERNAL_106 1
#define ZE_MACRO_BOOL_INTERNAL_107 1
#define ZE_MACRO_BOOL_INTERNAL_108 1
#define ZE_MACRO_BOOL_INTERNAL_109 1
#define ZE_MACRO_BOOL_INTERNAL_110 1
#define ZE_MACRO_BOOL_INTERNAL_111 1
#define ZE_MACRO_BOOL_INTERNAL_112 1
#define ZE_MACRO_BOOL_INTERNAL_113 1
#define ZE_MACRO_BOOL_INTERNAL_114 1
#define ZE_MACRO_BOOL_INTERNAL_115 1
#define ZE_MACRO_BOOL_INTERNAL_116 1
#define ZE_MACRO_BOOL_INTERNAL_117 1
#define ZE_MACRO_BOOL_INTERNAL_118 1
#define ZE_MACRO_BOOL_INTERNAL_119 1
#define ZE_MACRO_BOOL_INTERNAL_120 1
#define ZE_MACRO_BOOL_INTERNAL_121 1
#define ZE_MACRO_BOOL_INTERNAL_122 1
#define ZE_MACRO_BOOL_INTERNAL_123 1
#define ZE_MACRO_BOOL_INTERNAL_124 1
#define ZE_MACRO_BOOL_INTERNAL_125 1
#define ZE_MACRO_BOOL_INTERNAL_126 1
#define ZE_MACRO_BOOL_INTERNAL_127 1
#define ZE_MACRO_BOOL_INTERNAL_128 1
#define ZE_MACRO_BOOL_INTERNAL_129 1
#define ZE_MACRO_BOOL_INTERNAL_130 1
#define ZE_MACRO_BOOL_INTERNAL_131 1
#define ZE_MACRO_BOOL_INTERNAL_132 1
#define ZE_MACRO_BOOL_INTERNAL_133 1
#define ZE_MACRO_BOOL_INTERNAL_134 1
#define ZE_MACRO_BOOL_INTERNAL_135 1
#define ZE_MACRO_BOOL_INTERNAL_136 1
#define ZE_MACRO_BOOL_INTERNAL_137 1
#define ZE_MACRO_BOOL_INTERNAL_138 1
#define ZE_MACRO_BOOL_INTERNAL_139 1
#define ZE_MACRO_BOOL_INTERNAL_140 1
#define ZE_MACRO_BOOL_INTERNAL_141 1
#define ZE_MACRO_BOOL_INTERNAL_142 1
#define ZE_MACRO_BOOL_INTERNAL_143 1
#define ZE_MACRO_BOOL_INTERNAL_144 1
#define ZE_MACRO_BOOL_INTERNAL_145 1
#define ZE_MACRO_BOOL_INTERNAL_146 1
#define ZE_MACRO_BOOL_INTERNAL_147 1
#define ZE_MACRO_BOOL_INTERNAL_148 1
#define ZE_MACRO_BOOL_INTERNAL_149 1
#define ZE_MACRO_BOOL_INTERNAL_150 1
#define ZE_MACRO_BOOL_INTERNAL_151 1
#define ZE_MACRO_BOOL_INTERNAL_152 1
#define ZE_MACRO_BOOL_INTERNAL_153 1
#define ZE_MACRO_BOOL_INTERNAL_154 1
#define ZE_MACRO_BOOL_INTERNAL_155 1
#define ZE_MACRO_BOOL_INTERNAL_156 1
#define ZE_MACRO_BOOL_INTERNAL_157 1
#define ZE_MACRO_BOOL_INTERNAL_158 1
#define ZE_MACRO_BOOL_INTERNAL_159 1
#define ZE_MACRO_BOOL_INTERNAL_160 1
#define ZE_MACRO_BOOL_INTERNAL_161 1
#define ZE_MACRO_BOOL_INTERNAL_162 1
#define ZE_MACRO_BOOL_INTERNAL_163 1
#define ZE_MACRO_BOOL_INTERNAL_164 1
#define ZE_MACRO_BOOL_INTERNAL_165 1
#define ZE_MACRO_BOOL_INTERNAL_166 1
#define ZE_MACRO_BOOL_INTERNAL_167 1
#define ZE_MACRO_BOOL_INTERNAL_168 1
#define ZE_MACRO_BOOL_INTERNAL_169 1
#define ZE_MACRO_BOOL_INTERNAL_170 1
#define ZE_MACRO_BOOL_INTERNAL_171 1
#define ZE_MACRO_BOOL_INTERNAL_172 1
#define ZE_MACRO_BOOL_INTERNAL_173 1
#define ZE_MACRO_BOOL_INTERNAL_174 1
#define ZE_MACRO_BOOL_INTERNAL_175 1
#define ZE_MACRO_BOOL_INTERNAL_176 1
#define ZE_MACRO_BOOL_INTERNAL_177 1
#define ZE_MACRO_BOOL_INTERNAL_178 1
#define ZE_MACRO_BOOL_INTERNAL_179 1
#define ZE_MACRO_BOOL_INTERNAL_180 1
#define ZE_MACRO_BOOL_INTERNAL_181 1
#define ZE_MACRO_BOOL_INTERNAL_182 1
#define ZE_MACRO_BOOL_INTERNAL_183 1
#define ZE_MACRO_BOOL_INTERNAL_184 1
#define ZE_MACRO_BOOL_INTERNAL_185 1
#define ZE_MACRO_BOOL_INTERNAL_186 1
#define ZE_MACRO_BOOL_INTERNAL_187 1
#define ZE_MACRO_BOOL_INTERNAL_188 1
#define ZE_MACRO_BOOL_INTERNAL_189 1
#define ZE_MACRO_BOOL_INTERNAL_190 1
#define ZE_MACRO_BOOL_INTERNAL_191 1
#define ZE_MACRO_BOOL_INTERNAL_192 1
#define ZE_MACRO_BOOL_INTERNAL_193 1
#define ZE_MACRO_BOOL_INTERNAL_194 1
#define ZE_MACRO_BOOL_INTERNAL_195 1
#define ZE_MACRO_BOOL_INTERNAL_196 1
#define ZE_MACRO_BOOL_INTERNAL_197 1
#define ZE_MACRO_BOOL_INTERNAL_198 1
#define ZE_MACRO_BOOL_INTERNAL_199 1
#define ZE_MACRO_BOOL_INTERNAL_200 1
#define ZE_MACRO_BOOL_INTERNAL_201 1
#define ZE_MACRO_BOOL_INTERNAL_202 1
#define ZE_MACRO_BOOL_INTERNAL_203 1
#define ZE_MACRO_BOOL_INTERNAL_204 1
#define ZE_MACRO_BOOL_INTERNAL_205 1
#define ZE_MACRO_BOOL_INTERNAL_206 1
#define ZE_MACRO_BOOL_INTERNAL_207 1
#define ZE_MACRO_BOOL_INTERNAL_208 1
#define ZE_MACRO_BOOL_INTERNAL_209 1
#define ZE_MACRO_BOOL_INTERNAL_210 1
#define ZE_MACRO_BOOL_INTERNAL_211 1
#define ZE_MACRO_BOOL_INTERNAL_212 1
#define ZE_MACRO_BOOL_INTERNAL_213 1
#define ZE_MACRO_BOOL_INTERNAL_214 1
#define ZE_MACRO_BOOL_INTERNAL_215 1
#define ZE_MACRO_BOOL_INTERNAL_216 1
#define ZE_MACRO_BOOL_INTERNAL_217 1
#define ZE_MACRO_BOOL_INTERNAL_218 1
#define ZE_MACRO_BOOL_INTERNAL_219 1
#define ZE_MACRO_BOOL_INTERNAL_220 1
#define ZE_MACRO_BOOL_INTERNAL_221 1
#define ZE_MACRO_BOOL_INTERNAL_222 1
#define ZE_MACRO_BOOL_INTERNAL_223 1
#define ZE_MACRO_BOOL_INTERNAL_224 1
#define ZE_MACRO_BOOL_INTERNAL_225 1
#define ZE_MACRO_BOOL_INTERNAL_226 1
#define ZE_MACRO_BOOL_INTERNAL_227 1
#define ZE_MACRO_BOOL_INTERNAL_228 1
#define ZE_MACRO_BOOL_INTERNAL_229 1
#define ZE_MACRO_BOOL_INTERNAL_230 1
#define ZE_MACRO_BOOL_INTERNAL_231 1
#define ZE_MACRO_BOOL_INTERNAL_232 1
#define ZE_MACRO_BOOL_INTERNAL_233 1
#define ZE_MACRO_BOOL_INTERNAL_234 1
#define ZE_MACRO_BOOL_INTERNAL_235 1
#define ZE_MACRO_BOOL_INTERNAL_236 1
#define ZE_MACRO_BOOL_INTERNAL_237 1
#define ZE_MACRO_BOOL_INTERNAL_238 1
#define ZE_MACRO_BOOL_INTERNAL_239 1
#define ZE_MACRO_BOOL_INTERNAL_240 1
#define ZE_MACRO_BOOL_INTERNAL_241 1
#define ZE_MACRO_BOOL_INTERNAL_242 1
#define ZE_MACRO_BOOL_INTERNAL_243 1
#define ZE_MACRO_BOOL_INTERNAL_244 1
#define ZE_MACRO_BOOL_INTERNAL_245 1
#define ZE_MACRO_BOOL_INTERNAL_246 1
#define ZE_MACRO_BOOL_INTERNAL_247 1
#define ZE_MACRO_BOOL_INTERNAL_248 1
#define ZE_MACRO_BOOL_INTERNAL_249 1
#define ZE_MACRO_BOOL_INTERNAL_250 1
#define ZE_MACRO_BOOL_INTERNAL_251 1
#define ZE_MACRO_BOOL_INTERNAL_252 1
#define ZE_MACRO_BOOL_INTERNAL_253 1
#define ZE_MACRO_BOOL_INTERNAL_254 1
#define ZE_MACRO_BOOL_INTERNAL_255 1

#endif
