//ZE_SOURCE_PROCESSOR_START(License, 1.0)
/*******************************************************************************
 Zinek Engine - ZEDMenu.h
 ------------------------------------------------------------------------------
 Copyright (C) 2008-2021 Yiğit Orçun GÖKBULUT. All rights reserved.

 This file is part of the Zinek Engine  Software. Zinek Engine Software and the
 accompanying  materials are  made available  under the  terms of Zinek  Engine
 Commercial License or the GNU General Public License Version 3.

                      ZINEK ENGINE COMMERCIAL LICENSE
 Licensees  holding  valid  Zinek Engine Commercial  License(s) may  use  Zinek
 Engine  Software in  accordance  with   the  commercial  license  agreement(s)
 (which can only be  issued  by  copyright  owner "Yiğit  Orçun  GÖKBULUT") and
 provided with the Software  or, alternatively,  in  accordance with the  terms
 contained  in  a  written  agreement  between  you  and  copyright  owner. For
 licensing  terms  and conditions  please  contact  with  copyright owner.

                    GNU GENERAL PUBLIC LICENSE VERSION 3
 This program is free software: you can  redistribute it and/or modify it under
 the terms of the GNU General Public  License as published by the Free Software
 Foundation, either  version 3 of  the License, or  (at your option)  any later
 version. This program is  distributed in the hope that  it will be useful, but
 WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See  the GNU General Public License for more
 details. You  should have received  a copy of the  GNU General  Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>.

 Copyright Owner Information:
  Name: Yiğit Orçun GÖKBULUT
  Contact: orcun.gokbulut@gmail.com
  Github: https://www.github.com/orcun-gokbulut/ZE
*******************************************************************************/
//ZE_SOURCE_PROCESSOR_END()

#pragma once

#include <QObject>

#include "ZEDS/ZEArray.h"
#include "ZEDS/ZEDelegate.h"

class QMenu;
class QMenuBar;
class QAction;
class ZEDMenu;

typedef ZEDelegate<void (ZEDMenu* Menu)> ZEDMenuCallback;

class ZEDMenu : public QObject
{
	friend class ZEDMainWindow;
	private:
		ZEDMenu*							Parent;
		ZEString							Name;
		ZEString							Section;
		ZEString							IconPath;
		bool								Checkable;
		bool								Checked;
		bool								AutoGenerated;

		ZEArray<ZEDMenu*>					ChildMenus;

		QMenu*								Menu;
		QAction*							Action;
		QMenuBar*							MenuBar;
		void*								UserData;
		ZEDMenuCallback						Callback;

		void								Update();

	private slots:
		void								Action_triggered();

	public:
		ZEDMenu*							GetParent();

		void								SetName(const ZEString&	 Name);
		ZEString							GetName() const;

		void								SetSection(const ZEString& Name);
		const ZEString&						GetSection() const;

		void								SetIconPath(const ZEString&	Name);
		const ZEString&						GetIconPath() const;

		void								SetEnabled(bool Enabled);
		bool								GetEnabled() const;

		void								SetVisible(bool Enabled);
		bool								GetVisible() const;
	
		void								SetCheckable(bool Checkable);
		bool								GetCheckable();

		void								SetChecked(bool Checked);
		bool								GetChecked();

		void								SetUserData(void* Data);
		void*								GetUserData();

		void								SetCallback(const ZEDMenuCallback& Callback);
		const ZEDMenuCallback&				GetCallback();

		const ZEArray<ZEDMenu*>&			GetMenus() const;
		void								AddMenu(ZEDMenu* Menu);
		void								AddMenu(const ZEString& Path, ZEDMenu* Menu);
		bool								RemoveMenu(ZEDMenu* Item);
		
											ZEDMenu();
											~ZEDMenu();
};

